# Generated by Django 5.1 on 2024-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_router_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='router',
            name='decrypted_key',
            field=models.FileField(blank=True, null=True, upload_to='keys/'),
        ),
    ]
