# Generated by Django 5.1 on 2024-09-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_router_certificate_router_decrypted_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='certificate',
            new_name='cert_webfig',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='decrypted_key',
            new_name='cert_webfig_decrypt',
        ),
    ]
