apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-beat-config
  labels:
    app: celery-beat
data:
  CELERY_BROKER: redis://redis:6379/0
  CELERY_BACKEND: redis://redis:6379/0
  DATABASE_NAME: mikrotikapi
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"