# Generated by Django 5.1 on 2024-09-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_testdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testDB',
        ),
    ]
