# Generated by Django 5.1 on 2024-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_smscredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='createclientsms',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='createservicesms',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nearduesms',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentreceivedsms',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='smscredentials',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suspendedsms',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
    ]
