# Generated by Django 5.1 on 2024-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_createclientsms_custom_id_createservicesms_custom_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateServiceSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_id', models.IntegerField(default=1)),
            ],
        ),
    ]
