# Generated by Django 5.1.1 on 2024-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_activateservicesms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
