# Generated by Django 5.1.1 on 2024-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_sms_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='length',
            field=models.IntegerField(default=1),
        ),
    ]
