apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: peetahdarius/mikrotik-system-frontend
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/config.json
            subPath: config.json
        # env:
        #   - name:  REACT_APP_BACKEND_URL
        #     valueFrom:
        #       configMapKeyRef:
        #         name: frontend-config
        #         key:  REACT_APP_BACKEND_URL
        #   - name:  REACT_APP_BACKEND_HTTP_URL
        #     valueFrom:
        #       configMapKeyRef:
        #         name: frontend-config
        #         key:  REACT_APP_BACKEND_HTTP_URL
        #   - name:  REACT_APP_WEBSOCKET_URL
        #     valueFrom:
        #       configMapKeyRef:
        #         name: frontend-config
        #         key:  REACT_APP_WEBSOCKET_URL
        ports:
          - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
            items:
              - key: config.json
                path: config.json
      