apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  config.json: |
    {
      "REACT_APP_BACKEND_URL": "backend",
      "REACT_APP_BACKEND_HTTP_URL": "backend",
      "REACT_APP_WEBSOCKET_URL": "wss://backend/ws/"
    }
