# Generated by Django 5.1 on 2024-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_server', '0002_alter_pppserver_max_mru_alter_pppserver_max_mtu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pppserver',
            name='max_mru',
            field=models.IntegerField(blank=True, default='auto', null=True),
        ),
        migrations.AlterField(
            model_name='pppserver',
            name='max_mtu',
            field=models.IntegerField(blank=True, default='auto', null=True),
        ),
    ]
