# Generated by Django 5.1.1 on 2024-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0003_unificredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='unificredentials',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
    ]
