# Generated by Django 5.1.1 on 2024-09-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0004_unificredentials_custom_id'),
        ('hotspot_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfullConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('ap_mac', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='hotspot_packages.package')),
            ],
        ),
    ]
