# Generated by Django 5.1.1 on 2024-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0005_successfullconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='chackout_request_id',
            field=models.CharField(default='djjjsjsjsj', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempdata',
            name='merchant_request_id',
            field=models.CharField(default='djdjdjdjd', max_length=200),
            preserve_default=False,
        ),
    ]
