# Generated by Django 5.1.1 on 2024-09-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0006_tempdata_chackout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdata',
            old_name='chackout_request_id',
            new_name='checkout_request_id',
        ),
    ]
