# Generated by Django 5.1.1 on 2024-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0007_rename_chackout_request_id_tempdata_checkout_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=150)),
                ('ip', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
