# Generated by Django 5.1.1 on 2024-09-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0008_accesspoints'),
        ('hotspot_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successfullconnection',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='hotspot_packages.package'),
        ),
    ]
