# Generated by Django 5.1 on 2024-10-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpackage',
            name='expiry',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='staticpackage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
