# Generated by Django 5.1 on 2024-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailconfiguration_email_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
