# Generated by Django 5.1 on 2024-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailconfiguration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_host_user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
