# Generated by Django 5.1 on 2024-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcpservice',
            name='disabled',
        ),
        migrations.AddField(
            model_name='dhcpservice',
            name='suspended_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
