# Generated by Django 5.1 on 2024-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_service', '0002_remove_dhcpservice_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpservice',
            name='ip_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
