# Generated by Django 5.1 on 2024-11-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_service', '0003_alter_dhcpservice_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcpservice',
            name='suspended_service',
        ),
    ]
