# Generated by Django 5.1.1 on 2024-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_service', '0004_remove_dhcpservice_suspended_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpservice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
