# Generated by Django 5.1 on 2024-10-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='relay',
        ),
    ]
