# Generated by Django 5.1 on 2024-10-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_server', '0002_remove_server_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='default_limit',
            field=models.CharField(default='1M/1M', max_length=100),
        ),
    ]
