# Generated by Django 5.1.1 on 2024-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp_server', '0003_network_default_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='relay',
            field=models.CharField(default='8.8.8.8', max_length=50),
            preserve_default=False,
        ),
    ]
