# Generated by Django 5.1 on 2024-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.CharField(default='machakos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=-1.3772648, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=31.487382, max_digits=10),
            preserve_default=False,
        ),
    ]
