# Generated by Django 5.1 on 2024-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_balance_client_county_client_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='custom_id',
            field=models.CharField(max_length=50),
        ),
    ]
