# Generated by Django 5.1 on 2024-09-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_profile', '0002_pppprofile_dns_server_pppprofile_local_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pppprofile',
            old_name='dns_server',
            new_name='primary_dns',
        ),
    ]
