# Generated by Django 5.1 on 2024-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_profile', '0003_rename_dns_server_pppprofile_primary_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppprofile',
            name='expiry',
            field=models.IntegerField(default=30),
        ),
    ]
