apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: mikrotikapi
  POSTGRES_USER: root
  POSTGRES_MAX_CONNECTIONS: "1000"
  REPLICATION_USER: replication_user
