# Generated by Django 5.1 on 2024-08-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppservice',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
