# Generated by Django 5.1 on 2024-09-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_service', '0003_remove_pppservice_suspended_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pppservice',
            name='balance',
        ),
    ]
