# Generated by Django 5.1.1 on 2024-11-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_custom_id'),
        ('ppp_service', '0004_remove_pppservice_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pppservice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ppp_services', to='client.client'),
            preserve_default=False,
        ),
    ]
