# Generated by Django 5.1.1 on 2024-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppp_service', '0005_alter_pppservice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppservice',
            name='caller_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
