# Generated by Django 5.1 on 2024-09-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_pppservicepaymentlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PPPServicePayment',
        ),
    ]
