# Generated by Django 5.1 on 2024-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_pppservicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
