# Generated by Django 5.1 on 2024-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_cashpayment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=150)),
                ('acc_no_prefix', models.CharField(max_length=150)),
                ('consumer_key', models.TextField()),
                ('comsumer_secret', models.TextField()),
                ('confirmation_url', models.URLField()),
                ('validation_url', models.URLField()),
                ('custom_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
