# Generated by Django 5.1 on 2024-09-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_custom_id'),
        ('payment', '0006_rename_comsumer_secret_paymentdetails_consumer_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpayment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='service',
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_payments', to='client.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mpesa_payments', to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pppservicepaymentlogs',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_logs', to='client.client'),
        ),
    ]
