apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: db-migration
        image: peetahdarius/mikrotik-system-backend
        command: ["sh", "-c", "python manage.py migrate"]
        env:
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_NAME
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_PORT
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_HOST
          - name: CELERY_BACKEND
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: CELERY_BACKEND
          - name: CELERY_BROKER
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: CELERY_BROKER
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DATABASE_PASSWORD
      containers:
      - name: backend
        image: peetahdarius/mikrotik-system-backend
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_NAME
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_PORT
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DATABASE_HOST
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DATABASE_PASSWORD
