apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  DATABASE_NAME: mikrotikapi
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  CELERY_BROKER: redis://redis:6379/0
  CELERY_BACKEND: redis://redis:6379/0
