# Generated by Django 5.1.1 on 2024-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaExpressCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.URLField()),
                ('account_reference', models.CharField(max_length=200)),
                ('transaction_desc', models.TextField()),
                ('transaction_type', models.CharField(max_length=200)),
                ('short_code', models.CharField(max_length=50)),
                ('pass_key', models.TextField()),
                ('consumer_key', models.TextField()),
                ('consumer_secret', models.TextField()),
                ('party_b', models.CharField(max_length=50)),
                ('custom_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
